# Generated by Django 2.2.2 on 2020-09-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
