# Generated by Django 2.2.2 on 2020-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
                ('fare', models.CharField(max_length=200)),
                ('shop', models.CharField(max_length=200)),
                ('toppicture', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('shoplogo', models.CharField(max_length=200)),
                ('addTime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
