# Generated by Django 2.2.2 on 2020-09-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='standars',
            field=models.CharField(default='', max_length=200),
        ),
    ]
