# Generated by Django 2.2.2 on 2020-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_goods_standars'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField(max_length=200)),
                ('goodid', models.CharField(max_length=200)),
                ('goodname', models.CharField(max_length=200)),
                ('num', models.IntegerField(max_length=200)),
                ('orderid', models.CharField(max_length=200)),
                ('pic', models.CharField(max_length=500)),
                ('shop', models.CharField(max_length=200)),
                ('standarsname', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('creattime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='goods',
            name='toppicture',
            field=models.CharField(max_length=2000),
        ),
    ]
