# Generated by Django 2.2.2 on 2020-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200923_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='addTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
